# Generated by Django 5.1.4 on 2025-01-07 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='date',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfs.shelf')),
            ],
        ),
    ]
