# Generated by Django 5.1.4 on 2025-01-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0002_remove_shelf_date_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='shelf.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelf',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shelf',
            name='image',
            field=models.ImageField(default='shelf.png', upload_to=''),
        ),
    ]
