# Generated by Django 5.1.4 on 2025-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0003_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
