# Generated by Django 5.1.4 on 2025-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0003_item_content_item_image_item_quantity_shelf_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='https://static.thenounproject.com/png/4241034-200.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
