# Generated by Django 5.1.4 on 2025-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0004_alter_item_image_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
