# Generated by Django 5.1.4 on 2025-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0005_alter_item_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='shelf',
            name='order',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
