# Generated by Django 5.1.4 on 2025-02-15 11:50

import django.db.models.deletion
import shelfs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0005_alter_item_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../static/icons/item.svg', upload_to=shelfs.models.item_image_upload_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfs.item')),
            ],
        ),
    ]
