# Generated by Django 5.1.4 on 2025-02-15 12:13

import shelfs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0006_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='../static/icons/item.svg', upload_to=shelfs.models.item_add_images_upload_path),
        ),
    ]
