# Generated by Django 5.1.4 on 2025-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0006_alter_shelf_options_shelf_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
