# Generated by Django 5.1.4 on 2025-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0007_alter_item_content_alter_shelf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
