# Generated by Django 5.1.4 on 2025-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0008_alter_shelf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='image',
            field=models.ImageField(default='./static/icons/shelf.svg', upload_to=''),
        ),
    ]
