# Generated by Django 5.1.4 on 2025-01-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0009_alter_shelf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./static/icons/item.svg', upload_to=''),
        ),
    ]
