# Generated by Django 5.1.4 on 2025-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0014_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='shelfs\\static\\icons\\item.svg', upload_to=''),
        ),
    ]
