# Generated by Django 5.1.4 on 2025-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0016_alter_item_image_alter_shelf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='icons/item.svg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='image',
            field=models.ImageField(default='./static/icons/shelf.svg', upload_to='images'),
        ),
    ]
