# Generated by Django 5.1.4 on 2025-01-11 15:18

import shelfs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0018_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=shelfs.models.item_image_upload_path),
        ),
    ]
