# Generated by Django 5.1.4 on 2025-01-11 15:42

import shelfs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0022_alter_item_image_alter_shelf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='../static/icons/item.svg', upload_to=shelfs.models.item_image_upload_path),
        ),
    ]
